/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.admin.api.system.model.po;

import lombok.Data;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_file",comment="系统文件表",pk_constraint="PRIMARY")
public class SysFile implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6298328764454408611L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="文件id",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger id;

	@Column(name="file_name",comment="文件名称",length=200L,type=java.sql.Types.VARCHAR,nullable=false)
	private String fileName;

	@Column(name="file_suffix",comment="文件后缀",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String fileSuffix;

	@Column(name="real_path",comment="文件真实路径",length=500L,type=java.sql.Types.VARCHAR,nullable=false)
	private String realPath;

	@Column(name="file_size",comment="文件大小（单位：字节）",length=19L,defaultValue="0",type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger fileSize;

	@Column(name="create_by",comment="创建人",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	private BigInteger createBy;

	@Column(name="create_time",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;

	@Column(name="update_by",comment="更新人",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	private BigInteger updateBy;

	@Column(name="update_time",comment="更新时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime updateTime;

	@Column(name="is_share",comment="是否共享",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nullable=true)
	private Integer isShare;

	@Column(name="is_deleted",comment="是否删除",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nullable=false)
	private Integer isDeleted;
	/** default constructor */
	public SysFile() {
	}
	
	/** pk constructor */
	public SysFile(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
