/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.admin.api.system.model.po;

import lombok.Data;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_log",comment="系统操作日志表",pk_constraint="PRIMARY")
public class SysLog implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1755081321604283045L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="日志编号",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger id;

	@Column(name="ip_address",comment="请求ip地址",length=128L,type=java.sql.Types.VARCHAR,nullable=false)
	private String ipAddress;

	@Column(name="operator",comment="操作人员",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	private BigInteger operator;

	@Column(name="request_way",comment="请求方式",length=10L,type=java.sql.Types.VARCHAR,nullable=false)
	private String requestWay;

	@Column(name="log_status",comment="日志状态;0异常 1成功",length=3L,type=java.sql.Types.TINYINT,nullable=true)
	private Integer logStatus;

	@Column(name="log_type",comment="日志类型：1登录 2操作 ",length=3L,type=java.sql.Types.TINYINT,nullable=true)
	private Integer logType;

	@Column(name="create_time",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;
	/** default constructor */
	public SysLog() {
	}
	
	/** pk constructor */
	public SysLog(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
