/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.admin.api.system.model.po;

import lombok.Data;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_role",comment="系统角色表",pk_constraint="PRIMARY")
public class SysRole implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7162397489747142009L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="角色id",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger id;

	@Column(name="role_name",comment="角色名称",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	private String roleName;

	@Column(name="role_key",comment="角色标识",length=255L,type=java.sql.Types.VARCHAR,nullable=false)
	private String roleKey;

	@Column(name="remark",comment="备注",length=255L,type=java.sql.Types.VARCHAR,nullable=true)
	private String remark;

	@Column(name="sort",comment="显示排序",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	private Integer sort;

	@Column(name="create_by",comment="创建人",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger createBy;

	@Column(name="create_time",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;

	@Column(name="update_by",comment="更新人",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	private BigInteger updateBy;

	@Column(name="update_time",comment="更新时间",length=19L,type=java.sql.Types.DATE,nullable=true)
	private LocalDateTime updateTime;

	@Column(name="is_deleted",comment="是否删除",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nullable=false)
	private Integer isDeleted;

	@Column(name="revision",comment="乐观锁",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	private Integer revision;
	/** default constructor */
	public SysRole() {
	}
	
	/** pk constructor */
	public SysRole(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
