/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.admin.api.system.model.po;

import lombok.Data;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serializable;
import java.math.BigInteger;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_theme",comment="系统主题表",pk_constraint="PRIMARY")
public class SysTheme implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3878319810303218467L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="系统主题id",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger id;

	@Column(name="user_id",comment="用户id",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	private BigInteger userId;

	@Column(name="layout_mode",comment="布局模式：0默认",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nullable=false)
	private Integer layoutMode;

	@Column(name="primary_color",comment="主题颜色",length=8L,type=java.sql.Types.VARCHAR,nullable=true)
	private String primaryColor;

	@Column(name="color_2",comment="颜色2",length=8L,type=java.sql.Types.VARCHAR,nullable=true)
	private String color2;

	@Column(name="color_3",comment="颜色3",length=8L,type=java.sql.Types.VARCHAR,nullable=true)
	private String color3;

	@Column(name="color_4",comment="颜色4",length=8L,type=java.sql.Types.VARCHAR,nullable=true)
	private String color4;

	@Column(name="is_dark",comment="是否暗黑模式",length=3L,defaultValue="0",type=java.sql.Types.TINYINT,nullable=true)
	private Integer isDark;
	/** default constructor */
	public SysTheme() {
	}
	
	/** pk constructor */
	public SysTheme(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
