/**
 *@Generated by sagacity-quickvo 5.0
 */
package net.cocotea.admin.api.system.model.po;

import lombok.Data;
import lombok.experimental.Accessors;
import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sqltoy-quickstart
 * @author CoCoTea
 * @version 1.0.0 
 */
@Data
@Accessors(chain = true)
@Entity(tableName="sys_version",comment="系统版本更新记录表",pk_constraint="PRIMARY")
public class SysVersion implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4223242884003909511L;
/*---begin-auto-generate-don't-update-this-area--*/	

	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugins.id.impl.SnowflakeIdGenerator")
	@Column(name="id",comment="版本id",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger id;

	@Column(name="update_no",comment="更新版本号",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	private String updateNo;

	@Column(name="update_desc",comment="版本更新描述",length=900L,type=java.sql.Types.VARCHAR,nullable=true)
	private String updateDesc;

	@Column(name="platform_name",comment="系统平台名称",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	private String platformName;

	@Column(name="download_url",comment="下载地址",length=200L,type=java.sql.Types.VARCHAR,nullable=true)
	private String downloadUrl;

	@Column(name="create_by",comment="创建人",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	private BigInteger createBy;

	@Column(name="create_time",comment="创建时间",length=19L,type=java.sql.Types.DATE,nullable=false)
	private LocalDateTime createTime;

	@Column(name="update_by",comment="更新人",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	private BigInteger updateBy;

	@Column(name="update_time",comment="更新时间",length=19L,type=java.sql.Types.DATE,nullable=true)
	private LocalDateTime updateTime;
	/** default constructor */
	public SysVersion() {
	}
	
	/** pk constructor */
	public SysVersion(BigInteger id)
	{
		this.id=id;
	}
/*---end-auto-generate-don't-update-this-area--*/
}
