/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity.base;

import java.io.Serializable;
import java.util.List;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * Table: sys_menu,Remark:系统菜单表  
 */
@Entity(tableName="sys_menu",pk_constraint="PRIMARY")
public abstract class AbstractMenu implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8519958959361964627L;
	
	/**
	 * jdbcType:BIGINT
	 * 菜单ID
	 */
	@Id
	@Column(name="menu_id",length=19L,type=java.sql.Types.BIGINT,nullable=false,autoIncrement=true)
	protected BigInteger menuId;
	
	/**
	 * jdbcType:VARCHAR
	 * 菜单名称
	 */
	@Column(name="menu_name",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String menuName;
	
	/**
	 * jdbcType:BIGINT
	 * 父菜单ID
	 */
	@Column(name="parent_id",length=19L,defaultValue="0",type=java.sql.Types.BIGINT,nullable=true)
	protected BigInteger parentId;
	
	/**
	 * jdbcType:INT
	 * 显示顺序
	 */
	@Column(name="order_num",length=10L,defaultValue="0",type=java.sql.Types.INTEGER,nullable=true)
	protected Integer orderNum;
	
	/**
	 * jdbcType:VARCHAR
	 * 路由地址
	 */
	@Column(name="path",length=200L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String path;
	
	/**
	 * jdbcType:VARCHAR
	 * 组件路径
	 */
	@Column(name="component",length=255L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String component;
	
	/**
	 * jdbcType:INT
	 * 是否为外链（0是 1否）
	 */
	@Column(name="is_frame",length=10L,defaultValue="1",type=java.sql.Types.INTEGER,nullable=true)
	protected Integer isFrame;
	
	/**
	 * jdbcType:INT
	 * 是否缓存（0缓存 1不缓存）
	 */
	@Column(name="is_cache",length=10L,defaultValue="0",type=java.sql.Types.INTEGER,nullable=true)
	protected Integer isCache;
	
	/**
	 * jdbcType:CHAR
	 * 菜单类型（M目录 C菜单 F按钮）
	 */
	@Column(name="menu_type",length=1L,defaultValue="",type=java.sql.Types.CHAR,nullable=true)
	protected String menuType;
	
	/**
	 * jdbcType:CHAR
	 * 菜单状态（0显示 1隐藏）
	 */
	@Column(name="visible",length=1L,defaultValue="0",type=java.sql.Types.CHAR,nullable=true)
	protected String visible;
	
	/**
	 * jdbcType:CHAR
	 * 菜单状态（0正常 1停用）
	 */
	@Column(name="status",length=1L,defaultValue="0",type=java.sql.Types.CHAR,nullable=true)
	protected String status;
	
	/**
	 * jdbcType:VARCHAR
	 * 权限标识
	 */
	@Column(name="perms",length=100L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String perms;
	
	/**
	 * jdbcType:VARCHAR
	 * 菜单图标
	 */
	@Column(name="icon",length=100L,defaultValue="#",type=java.sql.Types.VARCHAR,nullable=true)
	protected String icon;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建者
	 */
	@Column(name="create_by",length=64L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Column(name="create_time",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 更新者
	 */
	@Column(name="update_by",length=64L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 更新时间
	 */
	@Column(name="update_time",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime updateTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 备注
	 */
	@Column(name="remark",length=500L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String remark;
	
	/**
	 * jdbcType:VARCHAR
	 * 主键id
	 */
	@Id
	@Column(name="ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String id;
	
	/**
	 * jdbcType:INT
	 * 乐观锁
	 */
	@Column(name="REVISION",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer revision;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建人
	 */
	@Column(name="CREATE_BY",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Column(name="CREATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 更新人
	 */
	@Column(name="UPDATE_BY",length=32L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 更新时间
	 */
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime updateTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 删除状态;0删除 1未删除
	 */
	@Column(name="DELETE_STATUS",length=255L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String deleteStatus;
	
	/**
	 * jdbcType:VARCHAR
	 * 菜单名称
	 */
	@Column(name="MENU_NAME",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String menuName;
	
	/**
	 * jdbcType:VARCHAR
	 * 权限编号
	 */
	@Column(name="PERMISSION_CODE",length=64L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String permissionCode;
	
	/**
	 * jdbcType:VARCHAR
	 * 路由地址
	 */
	@Column(name="ROUTER_PATH",length=255L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String routerPath;
	
	/**
	 * jdbcType:VARCHAR
	 * 父主键ID
	 */
	@Column(name="PARENT_ID",length=32L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String parentId;
	
	/**
	 * jdbcType:CHAR
	 * 按钮类型;0目录 1菜单 2按钮
	 */
	@Column(name="MENU_TYPE",length=1L,type=java.sql.Types.CHAR,nullable=false)
	protected String menuType;
	
	/**
	 * jdbcType:CHAR
	 * 是否菜单
	 */
	@Column(name="IS_MENU",length=1L,type=java.sql.Types.CHAR,nullable=false)
	protected String isMenu;
	
	/**
	 * jdbcType:INT
	 * 显示顺序
	 */
	@Column(name="SORT",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer sort;
	
	/**
	 * jdbcType:VARCHAR
	 * 组件路径
	 */
	@Column(name="COMPONENT_PATH",length=64L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String componentPath;
	
	/**
	 * jdbcType:CHAR
	 * 是否外链;0是 1否
	 */
	@Column(name="IS_EXTERNAL_LINK",length=1L,type=java.sql.Types.CHAR,nullable=false)
	protected String isExternalLink;
	
	/**
	 * jdbcType:VARCHAR
	 * 菜单图标
	 */
	@Column(name="ICON_PATH",length=255L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String iconPath;
	
	/** default constructor */
	public AbstractMenu() {
	}
	
	/** pk constructor */
	public AbstractMenu(BigInteger menuId,String id)
	{
		this.menuId=menuId;
		this.id=id;
	}
	
	/**
	 *@param menuId the menuId to set
	 */
	public void setMenuId(BigInteger menuId) {
		this.menuId=menuId;
	}
		
	/**
	 *@return the MenuId
	 */
	public BigInteger getMenuId() {
	    return this.menuId;
	}
	
	/**
	 *@param menuName the menuName to set
	 */
	public void setMenuName(String menuName) {
		this.menuName=menuName;
	}
		
	/**
	 *@return the MenuName
	 */
	public String getMenuName() {
	    return this.menuName;
	}
	
	/**
	 *@param parentId the parentId to set
	 */
	public void setParentId(BigInteger parentId) {
		this.parentId=parentId;
	}
		
	/**
	 *@return the ParentId
	 */
	public BigInteger getParentId() {
	    return this.parentId;
	}
	
	/**
	 *@param orderNum the orderNum to set
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum=orderNum;
	}
		
	/**
	 *@return the OrderNum
	 */
	public Integer getOrderNum() {
	    return this.orderNum;
	}
	
	/**
	 *@param path the path to set
	 */
	public void setPath(String path) {
		this.path=path;
	}
		
	/**
	 *@return the Path
	 */
	public String getPath() {
	    return this.path;
	}
	
	/**
	 *@param component the component to set
	 */
	public void setComponent(String component) {
		this.component=component;
	}
		
	/**
	 *@return the Component
	 */
	public String getComponent() {
	    return this.component;
	}
	
	/**
	 *@param isFrame the isFrame to set
	 */
	public void setIsFrame(Integer isFrame) {
		this.isFrame=isFrame;
	}
		
	/**
	 *@return the IsFrame
	 */
	public Integer getIsFrame() {
	    return this.isFrame;
	}
	
	/**
	 *@param isCache the isCache to set
	 */
	public void setIsCache(Integer isCache) {
		this.isCache=isCache;
	}
		
	/**
	 *@return the IsCache
	 */
	public Integer getIsCache() {
	    return this.isCache;
	}
	
	/**
	 *@param menuType the menuType to set
	 */
	public void setMenuType(String menuType) {
		this.menuType=menuType;
	}
		
	/**
	 *@return the MenuType
	 */
	public String getMenuType() {
	    return this.menuType;
	}
	
	/**
	 *@param visible the visible to set
	 */
	public void setVisible(String visible) {
		this.visible=visible;
	}
		
	/**
	 *@return the Visible
	 */
	public String getVisible() {
	    return this.visible;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param perms the perms to set
	 */
	public void setPerms(String perms) {
		this.perms=perms;
	}
		
	/**
	 *@return the Perms
	 */
	public String getPerms() {
	    return this.perms;
	}
	
	/**
	 *@param icon the icon to set
	 */
	public void setIcon(String icon) {
		this.icon=icon;
	}
		
	/**
	 *@return the Icon
	 */
	public String getIcon() {
	    return this.icon;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param menuName the menuName to set
	 */
	public void setMenuName(String menuName) {
		this.menuName=menuName;
	}
		
	/**
	 *@return the MenuName
	 */
	public String getMenuName() {
	    return this.menuName;
	}
	
	/**
	 *@param permissionCode the permissionCode to set
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode=permissionCode;
	}
		
	/**
	 *@return the PermissionCode
	 */
	public String getPermissionCode() {
	    return this.permissionCode;
	}
	
	/**
	 *@param routerPath the routerPath to set
	 */
	public void setRouterPath(String routerPath) {
		this.routerPath=routerPath;
	}
		
	/**
	 *@return the RouterPath
	 */
	public String getRouterPath() {
	    return this.routerPath;
	}
	
	/**
	 *@param parentId the parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId=parentId;
	}
		
	/**
	 *@return the ParentId
	 */
	public String getParentId() {
	    return this.parentId;
	}
	
	/**
	 *@param menuType the menuType to set
	 */
	public void setMenuType(String menuType) {
		this.menuType=menuType;
	}
		
	/**
	 *@return the MenuType
	 */
	public String getMenuType() {
	    return this.menuType;
	}
	
	/**
	 *@param isMenu the isMenu to set
	 */
	public void setIsMenu(String isMenu) {
		this.isMenu=isMenu;
	}
		
	/**
	 *@return the IsMenu
	 */
	public String getIsMenu() {
	    return this.isMenu;
	}
	
	/**
	 *@param sort the sort to set
	 */
	public void setSort(Integer sort) {
		this.sort=sort;
	}
		
	/**
	 *@return the Sort
	 */
	public Integer getSort() {
	    return this.sort;
	}
	
	/**
	 *@param componentPath the componentPath to set
	 */
	public void setComponentPath(String componentPath) {
		this.componentPath=componentPath;
	}
		
	/**
	 *@return the ComponentPath
	 */
	public String getComponentPath() {
	    return this.componentPath;
	}
	
	/**
	 *@param isExternalLink the isExternalLink to set
	 */
	public void setIsExternalLink(String isExternalLink) {
		this.isExternalLink=isExternalLink;
	}
		
	/**
	 *@return the IsExternalLink
	 */
	public String getIsExternalLink() {
	    return this.isExternalLink;
	}
	
	/**
	 *@param iconPath the iconPath to set
	 */
	public void setIconPath(String iconPath) {
		this.iconPath=iconPath;
	}
		
	/**
	 *@return the IconPath
	 */
	public String getIconPath() {
	    return this.iconPath;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("menuId=").append(getMenuId()).append("\n");
		columnsBuffer.append("menuName=").append(getMenuName()).append("\n");
		columnsBuffer.append("parentId=").append(getParentId()).append("\n");
		columnsBuffer.append("orderNum=").append(getOrderNum()).append("\n");
		columnsBuffer.append("path=").append(getPath()).append("\n");
		columnsBuffer.append("component=").append(getComponent()).append("\n");
		columnsBuffer.append("isFrame=").append(getIsFrame()).append("\n");
		columnsBuffer.append("isCache=").append(getIsCache()).append("\n");
		columnsBuffer.append("menuType=").append(getMenuType()).append("\n");
		columnsBuffer.append("visible=").append(getVisible()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		columnsBuffer.append("perms=").append(getPerms()).append("\n");
		columnsBuffer.append("icon=").append(getIcon()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("remark=").append(getRemark()).append("\n");
		columnsBuffer.append("id=").append(getId()).append("\n");
		columnsBuffer.append("revision=").append(getRevision()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("deleteStatus=").append(getDeleteStatus()).append("\n");
		columnsBuffer.append("menuName=").append(getMenuName()).append("\n");
		columnsBuffer.append("permissionCode=").append(getPermissionCode()).append("\n");
		columnsBuffer.append("routerPath=").append(getRouterPath()).append("\n");
		columnsBuffer.append("parentId=").append(getParentId()).append("\n");
		columnsBuffer.append("menuType=").append(getMenuType()).append("\n");
		columnsBuffer.append("isMenu=").append(getIsMenu()).append("\n");
		columnsBuffer.append("sort=").append(getSort()).append("\n");
		columnsBuffer.append("componentPath=").append(getComponentPath()).append("\n");
		columnsBuffer.append("isExternalLink=").append(getIsExternalLink()).append("\n");
		columnsBuffer.append("iconPath=").append(getIconPath()).append("\n");
		return columnsBuffer.toString();
	}
	
}
