/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity.base;

import java.io.Serializable;
import java.util.List;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * Table: sys_user,Remark:系统用户表  
 */
@Entity(tableName="sys_user",pk_constraint="PRIMARY")
public abstract class AbstractUser implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2226258204062532316L;
	
	/**
	 * jdbcType:BIGINT
	 * 用户ID
	 */
	@Id
	@Column(name="user_id",length=19L,type=java.sql.Types.BIGINT,nullable=false,autoIncrement=true)
	protected BigInteger userId;
	
	/**
	 * jdbcType:BIGINT
	 * 部门ID
	 */
	@Column(name="dept_id",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	protected BigInteger deptId;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户账号
	 */
	@Column(name="user_name",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String user_Name;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户昵称
	 */
	@Column(name="nick_name",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String nick_Name;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户类型（00系统用户）
	 */
	@Column(name="user_type",length=2L,defaultValue="0",type=java.sql.Types.VARCHAR,nullable=true)
	protected String userType;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户邮箱
	 */
	@Column(name="email",length=50L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String email;
	
	/**
	 * jdbcType:VARCHAR
	 * 手机号码
	 */
	@Column(name="phonenumber",length=11L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String phonenumber;
	
	/**
	 * jdbcType:CHAR
	 * 用户性别（0男 1女 2未知）
	 */
	@Column(name="sex",length=1L,defaultValue="0",type=java.sql.Types.CHAR,nullable=true)
	protected String sex;
	
	/**
	 * jdbcType:VARCHAR
	 * 头像地址
	 */
	@Column(name="avatar",length=100L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String avatar;
	
	/**
	 * jdbcType:VARCHAR
	 * 密码
	 */
	@Column(name="password",length=100L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String password;
	
	/**
	 * jdbcType:CHAR
	 * 帐号状态（0正常 1停用）
	 */
	@Column(name="status",length=1L,defaultValue="0",type=java.sql.Types.CHAR,nullable=true)
	protected String status;
	
	/**
	 * jdbcType:CHAR
	 * 删除标志（0代表存在 2代表删除）
	 */
	@Column(name="del_flag",length=1L,defaultValue="0",type=java.sql.Types.CHAR,nullable=true)
	protected String delFlag;
	
	/**
	 * jdbcType:VARCHAR
	 * 最后登录IP
	 */
	@Column(name="login_ip",length=128L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String loginIp;
	
	/**
	 * jdbcType:DATETIME
	 * 最后登录时间
	 */
	@Column(name="login_date",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime loginDate;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建者
	 */
	@Column(name="create_by",length=64L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Column(name="create_time",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 更新者
	 */
	@Column(name="update_by",length=64L,defaultValue="",type=java.sql.Types.VARCHAR,nullable=true)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 更新时间
	 */
	@Column(name="update_time",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime updateTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 备注
	 */
	@Column(name="remark",length=500L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String remark;
	
	/**
	 * jdbcType:VARCHAR
	 * 主键id
	 */
	@Id
	@Column(name="ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String id;
	
	/**
	 * jdbcType:INT
	 * 乐观锁
	 */
	@Column(name="REVISION",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer revision;
	
	/**
	 * jdbcType:VARCHAR
	 * 创建人
	 */
	@Column(name="CREATE_BY",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String createBy;
	
	/**
	 * jdbcType:DATETIME
	 * 创建时间
	 */
	@Column(name="CREATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=false)
	protected LocalDateTime createTime;
	
	/**
	 * jdbcType:VARCHAR
	 * 更新人
	 */
	@Column(name="UPDATE_BY",length=32L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String updateBy;
	
	/**
	 * jdbcType:DATETIME
	 * 更新时间
	 */
	@Column(name="UPDATE_TIME",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime updateTime;
	
	/**
	 * jdbcType:CHAR
	 * 删除状态;0删除 1未删除
	 */
	@Column(name="DELETE_STATUS",length=1L,type=java.sql.Types.CHAR,nullable=false)
	protected String deleteStatus;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户账号
	 */
	@Column(name="USERNAME",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String username;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户昵称
	 */
	@Column(name="NICKNAME",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String nickname;
	
	/**
	 * jdbcType:VARCHAR
	 * 密码
	 */
	@Column(name="PASSWORD",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String password;
	
	/**
	 * jdbcType:CHAR
	 * 用户性别;0未知 1男 2女
	 */
	@Column(name="SEX",length=1L,type=java.sql.Types.CHAR,nullable=false)
	protected String sex;
	
	/**
	 * jdbcType:VARCHAR
	 * 用户邮箱
	 */
	@Column(name="EMAIL",length=64L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String email;
	
	/**
	 * jdbcType:VARCHAR
	 * 手机号
	 */
	@Column(name="MOBILEPHONE",length=11L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String mobilephone;
	
	/**
	 * jdbcType:VARCHAR
	 * 部门id
	 */
	@Column(name="DEPARTMENT_ID",length=32L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String departmentId;
	
	/**
	 * jdbcType:CHAR
	 * 账号状态;0停用 1正常 2冻结 3封禁
	 */
	@Column(name="ACCOUNT_STATUS",length=1L,type=java.sql.Types.CHAR,nullable=false)
	protected String accountStatus;
	
	/**
	 * jdbcType:VARCHAR
	 * 头像地址
	 */
	@Column(name="AVATAR",length=255L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String avatar;
	
	/**
	 * jdbcType:VARCHAR
	 * 最后登录IP
	 */
	@Column(name="LAST_LOGIN_IP",length=64L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String lastLoginIp;
	
	/**
	 * jdbcType:DATETIME
	 * 最后登录时间
	 */
	@Column(name="LAST_LOGIN_TIME",length=19L,type=java.sql.Types.DATE,nullable=true)
	protected LocalDateTime lastLoginTime;
	
	/** default constructor */
	public AbstractUser() {
	}
	
	/** pk constructor */
	public AbstractUser(BigInteger userId,String id)
	{
		this.userId=userId;
		this.id=id;
	}
	
	/**
	 *@param userId the userId to set
	 */
	public void setUserId(BigInteger userId) {
		this.userId=userId;
	}
		
	/**
	 *@return the UserId
	 */
	public BigInteger getUserId() {
	    return this.userId;
	}
	
	/**
	 *@param deptId the deptId to set
	 */
	public void setDeptId(BigInteger deptId) {
		this.deptId=deptId;
	}
		
	/**
	 *@return the DeptId
	 */
	public BigInteger getDeptId() {
	    return this.deptId;
	}
	
	/**
	 *@param user_Name the user_Name to set
	 */
	public void setUser_Name(String user_Name) {
		this.user_Name=user_Name;
	}
		
	/**
	 *@return the User_Name
	 */
	public String getUser_Name() {
	    return this.user_Name;
	}
	
	/**
	 *@param nick_Name the nick_Name to set
	 */
	public void setNick_Name(String nick_Name) {
		this.nick_Name=nick_Name;
	}
		
	/**
	 *@return the Nick_Name
	 */
	public String getNick_Name() {
	    return this.nick_Name;
	}
	
	/**
	 *@param userType the userType to set
	 */
	public void setUserType(String userType) {
		this.userType=userType;
	}
		
	/**
	 *@return the UserType
	 */
	public String getUserType() {
	    return this.userType;
	}
	
	/**
	 *@param email the email to set
	 */
	public void setEmail(String email) {
		this.email=email;
	}
		
	/**
	 *@return the Email
	 */
	public String getEmail() {
	    return this.email;
	}
	
	/**
	 *@param phonenumber the phonenumber to set
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber=phonenumber;
	}
		
	/**
	 *@return the Phonenumber
	 */
	public String getPhonenumber() {
	    return this.phonenumber;
	}
	
	/**
	 *@param sex the sex to set
	 */
	public void setSex(String sex) {
		this.sex=sex;
	}
		
	/**
	 *@return the Sex
	 */
	public String getSex() {
	    return this.sex;
	}
	
	/**
	 *@param avatar the avatar to set
	 */
	public void setAvatar(String avatar) {
		this.avatar=avatar;
	}
		
	/**
	 *@return the Avatar
	 */
	public String getAvatar() {
	    return this.avatar;
	}
	
	/**
	 *@param password the password to set
	 */
	public void setPassword(String password) {
		this.password=password;
	}
		
	/**
	 *@return the Password
	 */
	public String getPassword() {
	    return this.password;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param delFlag the delFlag to set
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag=delFlag;
	}
		
	/**
	 *@return the DelFlag
	 */
	public String getDelFlag() {
	    return this.delFlag;
	}
	
	/**
	 *@param loginIp the loginIp to set
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp=loginIp;
	}
		
	/**
	 *@return the LoginIp
	 */
	public String getLoginIp() {
	    return this.loginIp;
	}
	
	/**
	 *@param loginDate the loginDate to set
	 */
	public void setLoginDate(LocalDateTime loginDate) {
		this.loginDate=loginDate;
	}
		
	/**
	 *@return the LoginDate
	 */
	public LocalDateTime getLoginDate() {
	    return this.loginDate;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param username the username to set
	 */
	public void setUsername(String username) {
		this.username=username;
	}
		
	/**
	 *@return the Username
	 */
	public String getUsername() {
	    return this.username;
	}
	
	/**
	 *@param nickname the nickname to set
	 */
	public void setNickname(String nickname) {
		this.nickname=nickname;
	}
		
	/**
	 *@return the Nickname
	 */
	public String getNickname() {
	    return this.nickname;
	}
	
	/**
	 *@param password the password to set
	 */
	public void setPassword(String password) {
		this.password=password;
	}
		
	/**
	 *@return the Password
	 */
	public String getPassword() {
	    return this.password;
	}
	
	/**
	 *@param sex the sex to set
	 */
	public void setSex(String sex) {
		this.sex=sex;
	}
		
	/**
	 *@return the Sex
	 */
	public String getSex() {
	    return this.sex;
	}
	
	/**
	 *@param email the email to set
	 */
	public void setEmail(String email) {
		this.email=email;
	}
		
	/**
	 *@return the Email
	 */
	public String getEmail() {
	    return this.email;
	}
	
	/**
	 *@param mobilephone the mobilephone to set
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone=mobilephone;
	}
		
	/**
	 *@return the Mobilephone
	 */
	public String getMobilephone() {
	    return this.mobilephone;
	}
	
	/**
	 *@param departmentId the departmentId to set
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId=departmentId;
	}
		
	/**
	 *@return the DepartmentId
	 */
	public String getDepartmentId() {
	    return this.departmentId;
	}
	
	/**
	 *@param accountStatus the accountStatus to set
	 */
	public void setAccountStatus(String accountStatus) {
		this.accountStatus=accountStatus;
	}
		
	/**
	 *@return the AccountStatus
	 */
	public String getAccountStatus() {
	    return this.accountStatus;
	}
	
	/**
	 *@param avatar the avatar to set
	 */
	public void setAvatar(String avatar) {
		this.avatar=avatar;
	}
		
	/**
	 *@return the Avatar
	 */
	public String getAvatar() {
	    return this.avatar;
	}
	
	/**
	 *@param lastLoginIp the lastLoginIp to set
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp=lastLoginIp;
	}
		
	/**
	 *@return the LastLoginIp
	 */
	public String getLastLoginIp() {
	    return this.lastLoginIp;
	}
	
	/**
	 *@param lastLoginTime the lastLoginTime to set
	 */
	public void setLastLoginTime(LocalDateTime lastLoginTime) {
		this.lastLoginTime=lastLoginTime;
	}
		
	/**
	 *@return the LastLoginTime
	 */
	public LocalDateTime getLastLoginTime() {
	    return this.lastLoginTime;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("userId=").append(getUserId()).append("\n");
		columnsBuffer.append("deptId=").append(getDeptId()).append("\n");
		columnsBuffer.append("user_Name=").append(getUser_Name()).append("\n");
		columnsBuffer.append("nick_Name=").append(getNick_Name()).append("\n");
		columnsBuffer.append("userType=").append(getUserType()).append("\n");
		columnsBuffer.append("email=").append(getEmail()).append("\n");
		columnsBuffer.append("phonenumber=").append(getPhonenumber()).append("\n");
		columnsBuffer.append("sex=").append(getSex()).append("\n");
		columnsBuffer.append("avatar=").append(getAvatar()).append("\n");
		columnsBuffer.append("password=").append(getPassword()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		columnsBuffer.append("delFlag=").append(getDelFlag()).append("\n");
		columnsBuffer.append("loginIp=").append(getLoginIp()).append("\n");
		columnsBuffer.append("loginDate=").append(getLoginDate()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("remark=").append(getRemark()).append("\n");
		columnsBuffer.append("id=").append(getId()).append("\n");
		columnsBuffer.append("revision=").append(getRevision()).append("\n");
		columnsBuffer.append("createBy=").append(getCreateBy()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("deleteStatus=").append(getDeleteStatus()).append("\n");
		columnsBuffer.append("username=").append(getUsername()).append("\n");
		columnsBuffer.append("nickname=").append(getNickname()).append("\n");
		columnsBuffer.append("password=").append(getPassword()).append("\n");
		columnsBuffer.append("sex=").append(getSex()).append("\n");
		columnsBuffer.append("email=").append(getEmail()).append("\n");
		columnsBuffer.append("mobilephone=").append(getMobilephone()).append("\n");
		columnsBuffer.append("departmentId=").append(getDepartmentId()).append("\n");
		columnsBuffer.append("accountStatus=").append(getAccountStatus()).append("\n");
		columnsBuffer.append("avatar=").append(getAvatar()).append("\n");
		columnsBuffer.append("lastLoginIp=").append(getLastLoginIp()).append("\n");
		columnsBuffer.append("lastLoginTime=").append(getLastLoginTime()).append("\n");
		return columnsBuffer.toString();
	}
	
}
