/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity.base;

import java.io.Serializable;
import java.util.List;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.math.BigInteger;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * Table: sys_role_menu,Remark:角色菜单关联表  
 */
@Entity(tableName="sys_role_menu",pk_constraint="PRIMARY")
public abstract class AbstractRoleMenu implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 462365854528365763L;
	
	/**
	 * jdbcType:BIGINT
	 * 角色ID
	 */
	@Id
	@Column(name="role_id",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	protected BigInteger roleId;
	
	/**
	 * jdbcType:BIGINT
	 * 菜单ID
	 */
	@Id
	@Column(name="menu_id",length=19L,type=java.sql.Types.BIGINT,nullable=false)
	protected BigInteger menuId;
	
	/**
	 * jdbcType:VARCHAR
	 * 角色主键ID
	 */
	@Column(name="ROLE_ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String roleId;
	
	/**
	 * jdbcType:VARCHAR
	 * 菜单主键ID
	 */
	@Column(name="MENU_ID",length=32L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String menuId;
	
	/** default constructor */
	public AbstractRoleMenu() {
	}
	
	/** pk constructor */
	public AbstractRoleMenu(BigInteger roleId,BigInteger menuId)
	{
		this.roleId=roleId;
		this.menuId=menuId;
	}
	
	/**
	 *@param roleId the roleId to set
	 */
	public void setRoleId(BigInteger roleId) {
		this.roleId=roleId;
	}
		
	/**
	 *@return the RoleId
	 */
	public BigInteger getRoleId() {
	    return this.roleId;
	}
	
	/**
	 *@param menuId the menuId to set
	 */
	public void setMenuId(BigInteger menuId) {
		this.menuId=menuId;
	}
		
	/**
	 *@return the MenuId
	 */
	public BigInteger getMenuId() {
	    return this.menuId;
	}
	
	/**
	 *@param roleId the roleId to set
	 */
	public void setRoleId(String roleId) {
		this.roleId=roleId;
	}
		
	/**
	 *@return the RoleId
	 */
	public String getRoleId() {
	    return this.roleId;
	}
	
	/**
	 *@param menuId the menuId to set
	 */
	public void setMenuId(String menuId) {
		this.menuId=menuId;
	}
		
	/**
	 *@return the MenuId
	 */
	public String getMenuId() {
	    return this.menuId;
	}


	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("roleId=").append(getRoleId()).append("\n");
		columnsBuffer.append("menuId=").append(getMenuId()).append("\n");
		columnsBuffer.append("roleId=").append(getRoleId()).append("\n");
		columnsBuffer.append("menuId=").append(getMenuId()).append("\n");
		return columnsBuffer.toString();
	}
	
}
