/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigInteger;
import java.time.LocalDateTime;
import com.jwss.system.entity.base.AbstractMenu;

/**
 * @project sss-rbac-admin
 * @author ${db.author}
 * @version 1.0.0
 * Table: sys_menu,Remark:系统菜单表 	
 */
@SqlToyEntity
public class Menu extends AbstractMenu {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5698424234803324100L;
	
	/** default constructor */
	public Menu() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public Menu(BigInteger menuId,String id)
	{
		this.menuId=menuId;
		this.id=id;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Menu clone() {
		try {
			return (Menu) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
