/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigInteger;
import com.jwss.system.entity.base.AbstractRoleMenu;

/**
 * @project sss-rbac-admin
 * @author ${db.author}
 * @version 1.0.0
 * Table: sys_role_menu,Remark:角色菜单关联表 	
 */
@SqlToyEntity
public class RoleMenu extends AbstractRoleMenu {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6844523408155256370L;
	
	/** default constructor */
	public RoleMenu() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public RoleMenu(BigInteger roleId,BigInteger menuId)
	{
		this.roleId=roleId;
		this.menuId=menuId;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public RoleMenu clone() {
		try {
			return (RoleMenu) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
