/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigInteger;
import java.time.LocalDateTime;
import com.jwss.system.entity.base.AbstractUser;

/**
 * @project sss-rbac-admin
 * @author ${db.author}
 * @version 1.0.0
 * Table: sys_user,Remark:系统用户表 	
 */
@SqlToyEntity
public class User extends AbstractUser {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3203290987069291273L;
	
	/** default constructor */
	public User() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public User(BigInteger userId,String id)
	{
		this.userId=userId;
		this.id=id;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public User clone() {
		try {
			return (User) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
