/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.entity;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigInteger;
import com.jwss.system.entity.base.AbstractUserRole;

/**
 * @project sss-rbac-admin
 * @author ${db.author}
 * @version 1.0.0
 * Table: sys_user_role,Remark:用户角色关联表 	
 */
@SqlToyEntity
public class UserRole extends AbstractUserRole {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7063853937784637106L;
	
	/** default constructor */
	public UserRole() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public UserRole(BigInteger userId,BigInteger roleId)
	{
		this.userId=userId;
		this.roleId=roleId;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public UserRole clone() {
		try {
			return (UserRole) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
