/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.vo;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * @description sys_menu,系统菜单表  
 */
public class MenuVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6856092554842076547L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 菜单ID
	 */
	private BigInteger menuId;
	
	/**
	 * 菜单名称
	 */
	private String menuName;
	
	/**
	 * 父菜单ID
	 */
	private BigInteger parentId;
	
	/**
	 * 显示顺序
	 */
	private Integer orderNum;
	
	/**
	 * 路由地址
	 */
	private String path;
	
	/**
	 * 组件路径
	 */
	private String component;
	
	/**
	 * 是否为外链（0是 1否）
	 */
	private Integer isFrame;
	
	/**
	 * 是否缓存（0缓存 1不缓存）
	 */
	private Integer isCache;
	
	/**
	 * 菜单类型（M目录 C菜单 F按钮）
	 */
	private String menuType;
	
	/**
	 * 菜单状态（0显示 1隐藏）
	 */
	private String visible;
	
	/**
	 * 菜单状态（0正常 1停用）
	 */
	private String status;
	
	/**
	 * 权限标识
	 */
	private String perms;
	
	/**
	 * 菜单图标
	 */
	private String icon;
	
	/**
	 * 创建者
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新者
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 备注
	 */
	private String remark;
	
	/**
	 * 主键id
	 */
	private String id;
	
	/**
	 * 乐观锁
	 */
	private Integer revision;
	
	/**
	 * 创建人
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新人
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 删除状态;0删除 1未删除
	 */
	private String deleteStatus;
	
	/**
	 * 菜单名称
	 */
	private String menuName;
	
	/**
	 * 权限编号
	 */
	private String permissionCode;
	
	/**
	 * 路由地址
	 */
	private String routerPath;
	
	/**
	 * 父主键ID
	 */
	private String parentId;
	
	/**
	 * 按钮类型;0目录 1菜单 2按钮
	 */
	private String menuType;
	
	/**
	 * 是否菜单
	 */
	private String isMenu;
	
	/**
	 * 显示顺序
	 */
	private Integer sort;
	
	/**
	 * 组件路径
	 */
	private String componentPath;
	
	/**
	 * 是否外链;0是 1否
	 */
	private String isExternalLink;
	
	/**
	 * 菜单图标
	 */
	private String iconPath;
	
	
	/**
	 *@param menuId the menuId to set
	 */
	public void setMenuId(BigInteger menuId) {
		this.menuId=menuId;
	}
		
	/**
	 *@return the MenuId
	 */
	public BigInteger getMenuId() {
	    return this.menuId;
	}
	
	/**
	 *@param menuName the menuName to set
	 */
	public void setMenuName(String menuName) {
		this.menuName=menuName;
	}
		
	/**
	 *@return the MenuName
	 */
	public String getMenuName() {
	    return this.menuName;
	}
	
	/**
	 *@param parentId the parentId to set
	 */
	public void setParentId(BigInteger parentId) {
		this.parentId=parentId;
	}
		
	/**
	 *@return the ParentId
	 */
	public BigInteger getParentId() {
	    return this.parentId;
	}
	
	/**
	 *@param orderNum the orderNum to set
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum=orderNum;
	}
		
	/**
	 *@return the OrderNum
	 */
	public Integer getOrderNum() {
	    return this.orderNum;
	}
	
	/**
	 *@param path the path to set
	 */
	public void setPath(String path) {
		this.path=path;
	}
		
	/**
	 *@return the Path
	 */
	public String getPath() {
	    return this.path;
	}
	
	/**
	 *@param component the component to set
	 */
	public void setComponent(String component) {
		this.component=component;
	}
		
	/**
	 *@return the Component
	 */
	public String getComponent() {
	    return this.component;
	}
	
	/**
	 *@param isFrame the isFrame to set
	 */
	public void setIsFrame(Integer isFrame) {
		this.isFrame=isFrame;
	}
		
	/**
	 *@return the IsFrame
	 */
	public Integer getIsFrame() {
	    return this.isFrame;
	}
	
	/**
	 *@param isCache the isCache to set
	 */
	public void setIsCache(Integer isCache) {
		this.isCache=isCache;
	}
		
	/**
	 *@return the IsCache
	 */
	public Integer getIsCache() {
	    return this.isCache;
	}
	
	/**
	 *@param menuType the menuType to set
	 */
	public void setMenuType(String menuType) {
		this.menuType=menuType;
	}
		
	/**
	 *@return the MenuType
	 */
	public String getMenuType() {
	    return this.menuType;
	}
	
	/**
	 *@param visible the visible to set
	 */
	public void setVisible(String visible) {
		this.visible=visible;
	}
		
	/**
	 *@return the Visible
	 */
	public String getVisible() {
	    return this.visible;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param perms the perms to set
	 */
	public void setPerms(String perms) {
		this.perms=perms;
	}
		
	/**
	 *@return the Perms
	 */
	public String getPerms() {
	    return this.perms;
	}
	
	/**
	 *@param icon the icon to set
	 */
	public void setIcon(String icon) {
		this.icon=icon;
	}
		
	/**
	 *@return the Icon
	 */
	public String getIcon() {
	    return this.icon;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param menuName the menuName to set
	 */
	public void setMenuName(String menuName) {
		this.menuName=menuName;
	}
		
	/**
	 *@return the MenuName
	 */
	public String getMenuName() {
	    return this.menuName;
	}
	
	/**
	 *@param permissionCode the permissionCode to set
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode=permissionCode;
	}
		
	/**
	 *@return the PermissionCode
	 */
	public String getPermissionCode() {
	    return this.permissionCode;
	}
	
	/**
	 *@param routerPath the routerPath to set
	 */
	public void setRouterPath(String routerPath) {
		this.routerPath=routerPath;
	}
		
	/**
	 *@return the RouterPath
	 */
	public String getRouterPath() {
	    return this.routerPath;
	}
	
	/**
	 *@param parentId the parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId=parentId;
	}
		
	/**
	 *@return the ParentId
	 */
	public String getParentId() {
	    return this.parentId;
	}
	
	/**
	 *@param menuType the menuType to set
	 */
	public void setMenuType(String menuType) {
		this.menuType=menuType;
	}
		
	/**
	 *@return the MenuType
	 */
	public String getMenuType() {
	    return this.menuType;
	}
	
	/**
	 *@param isMenu the isMenu to set
	 */
	public void setIsMenu(String isMenu) {
		this.isMenu=isMenu;
	}
		
	/**
	 *@return the IsMenu
	 */
	public String getIsMenu() {
	    return this.isMenu;
	}
	
	/**
	 *@param sort the sort to set
	 */
	public void setSort(Integer sort) {
		this.sort=sort;
	}
		
	/**
	 *@return the Sort
	 */
	public Integer getSort() {
	    return this.sort;
	}
	
	/**
	 *@param componentPath the componentPath to set
	 */
	public void setComponentPath(String componentPath) {
		this.componentPath=componentPath;
	}
		
	/**
	 *@return the ComponentPath
	 */
	public String getComponentPath() {
	    return this.componentPath;
	}
	
	/**
	 *@param isExternalLink the isExternalLink to set
	 */
	public void setIsExternalLink(String isExternalLink) {
		this.isExternalLink=isExternalLink;
	}
		
	/**
	 *@return the IsExternalLink
	 */
	public String getIsExternalLink() {
	    return this.isExternalLink;
	}
	
	/**
	 *@param iconPath the iconPath to set
	 */
	public void setIconPath(String iconPath) {
		this.iconPath=iconPath;
	}
		
	/**
	 *@return the IconPath
	 */
	public String getIconPath() {
	    return this.iconPath;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
