/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.vo;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * @description sys_menu,系统菜单表  
 */
public class MenuVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6856092554842076547L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 主键id
	 */
	private String id;
	
	/**
	 * 乐观锁
	 */
	private Integer revision;
	
	/**
	 * 创建人
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新人
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 删除状态;0删除 1未删除
	 */
	private String deleteStatus;
	
	/**
	 * 菜单名称
	 */
	private String menuName;
	
	/**
	 * 权限编号
	 */
	private String permissionCode;
	
	/**
	 * 路由地址
	 */
	private String routerPath;
	
	/**
	 * 父主键ID
	 */
	private String parentId;
	
	/**
	 * 按钮类型;0目录 1菜单 2按钮
	 */
	private String menuType;
	
	/**
	 * 是否菜单
	 */
	private String isMenu;
	
	/**
	 * 显示顺序
	 */
	private Integer sort;
	
	/**
	 * 组件路径
	 */
	private String componentPath;
	
	/**
	 * 是否外链;0是 1否
	 */
	private String isExternalLink;
	
	/**
	 * 菜单图标
	 */
	private String iconPath;
	
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param menuName the menuName to set
	 */
	public void setMenuName(String menuName) {
		this.menuName=menuName;
	}
		
	/**
	 *@return the MenuName
	 */
	public String getMenuName() {
	    return this.menuName;
	}
	
	/**
	 *@param permissionCode the permissionCode to set
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode=permissionCode;
	}
		
	/**
	 *@return the PermissionCode
	 */
	public String getPermissionCode() {
	    return this.permissionCode;
	}
	
	/**
	 *@param routerPath the routerPath to set
	 */
	public void setRouterPath(String routerPath) {
		this.routerPath=routerPath;
	}
		
	/**
	 *@return the RouterPath
	 */
	public String getRouterPath() {
	    return this.routerPath;
	}
	
	/**
	 *@param parentId the parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId=parentId;
	}
		
	/**
	 *@return the ParentId
	 */
	public String getParentId() {
	    return this.parentId;
	}
	
	/**
	 *@param menuType the menuType to set
	 */
	public void setMenuType(String menuType) {
		this.menuType=menuType;
	}
		
	/**
	 *@return the MenuType
	 */
	public String getMenuType() {
	    return this.menuType;
	}
	
	/**
	 *@param isMenu the isMenu to set
	 */
	public void setIsMenu(String isMenu) {
		this.isMenu=isMenu;
	}
		
	/**
	 *@return the IsMenu
	 */
	public String getIsMenu() {
	    return this.isMenu;
	}
	
	/**
	 *@param sort the sort to set
	 */
	public void setSort(Integer sort) {
		this.sort=sort;
	}
		
	/**
	 *@return the Sort
	 */
	public Integer getSort() {
	    return this.sort;
	}
	
	/**
	 *@param componentPath the componentPath to set
	 */
	public void setComponentPath(String componentPath) {
		this.componentPath=componentPath;
	}
		
	/**
	 *@return the ComponentPath
	 */
	public String getComponentPath() {
	    return this.componentPath;
	}
	
	/**
	 *@param isExternalLink the isExternalLink to set
	 */
	public void setIsExternalLink(String isExternalLink) {
		this.isExternalLink=isExternalLink;
	}
		
	/**
	 *@return the IsExternalLink
	 */
	public String getIsExternalLink() {
	    return this.isExternalLink;
	}
	
	/**
	 *@param iconPath the iconPath to set
	 */
	public void setIconPath(String iconPath) {
		this.iconPath=iconPath;
	}
		
	/**
	 *@return the IconPath
	 */
	public String getIconPath() {
	    return this.iconPath;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
