/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.vo;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * @description sys_role,系统角色表  
 */
public class RoleVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2107981556352042830L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 角色ID
	 */
	private BigInteger roleId;
	
	/**
	 * 角色名称
	 */
	private String roleName;
	
	/**
	 * 角色权限字符串
	 */
	private String roleKey;
	
	/**
	 * 显示顺序
	 */
	private Integer roleSort;
	
	/**
	 * 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
	 */
	private String dataScope;
	
	/**
	 * 菜单树选择项是否关联显示
	 */
	private Boolean menuCheckStrictly;
	
	/**
	 * 部门树选择项是否关联显示
	 */
	private Boolean deptCheckStrictly;
	
	/**
	 * 角色状态（0正常 1停用）
	 */
	private String status;
	
	/**
	 * 删除标志（0代表存在 2代表删除）
	 */
	private String delFlag;
	
	/**
	 * 创建者
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新者
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 备注
	 */
	private String remark;
	
	/**
	 * 主键id
	 */
	private String id;
	
	/**
	 * 乐观锁
	 */
	private Integer revision;
	
	/**
	 * 创建人
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新人
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 删除状态;0删除 1未删除
	 */
	private String deleteStatus;
	
	/**
	 * 角色名称
	 */
	private String roleName;
	
	/**
	 * 角色标识
	 */
	private String roleKey;
	
	/**
	 * 显示排序
	 */
	private Integer sort;
	
	/**
	 * 备注
	 */
	private String remark;
	
	
	/**
	 *@param roleId the roleId to set
	 */
	public void setRoleId(BigInteger roleId) {
		this.roleId=roleId;
	}
		
	/**
	 *@return the RoleId
	 */
	public BigInteger getRoleId() {
	    return this.roleId;
	}
	
	/**
	 *@param roleName the roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName=roleName;
	}
		
	/**
	 *@return the RoleName
	 */
	public String getRoleName() {
	    return this.roleName;
	}
	
	/**
	 *@param roleKey the roleKey to set
	 */
	public void setRoleKey(String roleKey) {
		this.roleKey=roleKey;
	}
		
	/**
	 *@return the RoleKey
	 */
	public String getRoleKey() {
	    return this.roleKey;
	}
	
	/**
	 *@param roleSort the roleSort to set
	 */
	public void setRoleSort(Integer roleSort) {
		this.roleSort=roleSort;
	}
		
	/**
	 *@return the RoleSort
	 */
	public Integer getRoleSort() {
	    return this.roleSort;
	}
	
	/**
	 *@param dataScope the dataScope to set
	 */
	public void setDataScope(String dataScope) {
		this.dataScope=dataScope;
	}
		
	/**
	 *@return the DataScope
	 */
	public String getDataScope() {
	    return this.dataScope;
	}
	
	/**
	 *@param menuCheckStrictly the menuCheckStrictly to set
	 */
	public void setMenuCheckStrictly(Boolean menuCheckStrictly) {
		this.menuCheckStrictly=menuCheckStrictly;
	}
		
	/**
	 *@return the MenuCheckStrictly
	 */
	public Boolean getMenuCheckStrictly() {
	    return this.menuCheckStrictly;
	}
	
	/**
	 *@param deptCheckStrictly the deptCheckStrictly to set
	 */
	public void setDeptCheckStrictly(Boolean deptCheckStrictly) {
		this.deptCheckStrictly=deptCheckStrictly;
	}
		
	/**
	 *@return the DeptCheckStrictly
	 */
	public Boolean getDeptCheckStrictly() {
	    return this.deptCheckStrictly;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param delFlag the delFlag to set
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag=delFlag;
	}
		
	/**
	 *@return the DelFlag
	 */
	public String getDelFlag() {
	    return this.delFlag;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param roleName the roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName=roleName;
	}
		
	/**
	 *@return the RoleName
	 */
	public String getRoleName() {
	    return this.roleName;
	}
	
	/**
	 *@param roleKey the roleKey to set
	 */
	public void setRoleKey(String roleKey) {
		this.roleKey=roleKey;
	}
		
	/**
	 *@return the RoleKey
	 */
	public String getRoleKey() {
	    return this.roleKey;
	}
	
	/**
	 *@param sort the sort to set
	 */
	public void setSort(Integer sort) {
		this.sort=sort;
	}
		
	/**
	 *@return the Sort
	 */
	public Integer getSort() {
	    return this.sort;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
