/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.vo;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * @description sys_role,系统角色表  
 */
public class RoleVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2107981556352042830L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 主键id
	 */
	private String id;
	
	/**
	 * 乐观锁
	 */
	private Integer revision;
	
	/**
	 * 创建人
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新人
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 删除状态;0删除 1未删除
	 */
	private String deleteStatus;
	
	/**
	 * 角色名称
	 */
	private String roleName;
	
	/**
	 * 角色标识
	 */
	private String roleKey;
	
	/**
	 * 显示排序
	 */
	private Integer sort;
	
	/**
	 * 备注
	 */
	private String remark;
	
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param roleName the roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName=roleName;
	}
		
	/**
	 *@return the RoleName
	 */
	public String getRoleName() {
	    return this.roleName;
	}
	
	/**
	 *@param roleKey the roleKey to set
	 */
	public void setRoleKey(String roleKey) {
		this.roleKey=roleKey;
	}
		
	/**
	 *@return the RoleKey
	 */
	public String getRoleKey() {
	    return this.roleKey;
	}
	
	/**
	 *@param sort the sort to set
	 */
	public void setSort(Integer sort) {
		this.sort=sort;
	}
		
	/**
	 *@return the Sort
	 */
	public Integer getSort() {
	    return this.sort;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
