/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.vo;

import java.io.Serializable;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * @description sys_user_role,用户角色关联表  
 */
public class UserRoleVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4531576278077869409L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 用户主键ID
	 */
	private String userId;
	
	/**
	 * 角色主键ID
	 */
	private String roleId;
	
	
	/**
	 *@param userId the userId to set
	 */
	public void setUserId(String userId) {
		this.userId=userId;
	}
		
	/**
	 *@return the UserId
	 */
	public String getUserId() {
	    return this.userId;
	}
	
	/**
	 *@param roleId the roleId to set
	 */
	public void setRoleId(String roleId) {
		this.roleId=roleId;
	}
		
	/**
	 *@return the RoleId
	 */
	public String getRoleId() {
	    return this.roleId;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
