/**
 *@Generated by sagacity-quickvo 5.0
 */
package com.jwss.system.vo;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;

/**
 * @project sss-rbac-admin
 * @version 1.0.0
 * @description sys_user,系统用户表  
 */
public class UserVO implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8964336332716926878L;
	
/*---begin-auto-generate-don't-update-this-area--*/	
	/**
	 * 用户ID
	 */
	private BigInteger userId;
	
	/**
	 * 部门ID
	 */
	private BigInteger deptId;
	
	/**
	 * 用户账号
	 */
	private String user_Name;
	
	/**
	 * 用户昵称
	 */
	private String nick_Name;
	
	/**
	 * 用户类型（00系统用户）
	 */
	private String userType;
	
	/**
	 * 用户邮箱
	 */
	private String email;
	
	/**
	 * 手机号码
	 */
	private String phonenumber;
	
	/**
	 * 用户性别（0男 1女 2未知）
	 */
	private String sex;
	
	/**
	 * 头像地址
	 */
	private String avatar;
	
	/**
	 * 密码
	 */
	private String password;
	
	/**
	 * 帐号状态（0正常 1停用）
	 */
	private String status;
	
	/**
	 * 删除标志（0代表存在 2代表删除）
	 */
	private String delFlag;
	
	/**
	 * 最后登录IP
	 */
	private String loginIp;
	
	/**
	 * 最后登录时间
	 */
	private LocalDateTime loginDate;
	
	/**
	 * 创建者
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新者
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 备注
	 */
	private String remark;
	
	/**
	 * 主键id
	 */
	private String id;
	
	/**
	 * 乐观锁
	 */
	private Integer revision;
	
	/**
	 * 创建人
	 */
	private String createBy;
	
	/**
	 * 创建时间
	 */
	private LocalDateTime createTime;
	
	/**
	 * 更新人
	 */
	private String updateBy;
	
	/**
	 * 更新时间
	 */
	private LocalDateTime updateTime;
	
	/**
	 * 删除状态;0删除 1未删除
	 */
	private String deleteStatus;
	
	/**
	 * 用户账号
	 */
	private String username;
	
	/**
	 * 用户昵称
	 */
	private String nickname;
	
	/**
	 * 密码
	 */
	private String password;
	
	/**
	 * 用户性别;0未知 1男 2女
	 */
	private String sex;
	
	/**
	 * 用户邮箱
	 */
	private String email;
	
	/**
	 * 手机号
	 */
	private String mobilephone;
	
	/**
	 * 部门id
	 */
	private String departmentId;
	
	/**
	 * 账号状态;0停用 1正常 2冻结 3封禁
	 */
	private String accountStatus;
	
	/**
	 * 头像地址
	 */
	private String avatar;
	
	/**
	 * 最后登录IP
	 */
	private String lastLoginIp;
	
	/**
	 * 最后登录时间
	 */
	private LocalDateTime lastLoginTime;
	
	
	/**
	 *@param userId the userId to set
	 */
	public void setUserId(BigInteger userId) {
		this.userId=userId;
	}
		
	/**
	 *@return the UserId
	 */
	public BigInteger getUserId() {
	    return this.userId;
	}
	
	/**
	 *@param deptId the deptId to set
	 */
	public void setDeptId(BigInteger deptId) {
		this.deptId=deptId;
	}
		
	/**
	 *@return the DeptId
	 */
	public BigInteger getDeptId() {
	    return this.deptId;
	}
	
	/**
	 *@param user_Name the user_Name to set
	 */
	public void setUser_Name(String user_Name) {
		this.user_Name=user_Name;
	}
		
	/**
	 *@return the User_Name
	 */
	public String getUser_Name() {
	    return this.user_Name;
	}
	
	/**
	 *@param nick_Name the nick_Name to set
	 */
	public void setNick_Name(String nick_Name) {
		this.nick_Name=nick_Name;
	}
		
	/**
	 *@return the Nick_Name
	 */
	public String getNick_Name() {
	    return this.nick_Name;
	}
	
	/**
	 *@param userType the userType to set
	 */
	public void setUserType(String userType) {
		this.userType=userType;
	}
		
	/**
	 *@return the UserType
	 */
	public String getUserType() {
	    return this.userType;
	}
	
	/**
	 *@param email the email to set
	 */
	public void setEmail(String email) {
		this.email=email;
	}
		
	/**
	 *@return the Email
	 */
	public String getEmail() {
	    return this.email;
	}
	
	/**
	 *@param phonenumber the phonenumber to set
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber=phonenumber;
	}
		
	/**
	 *@return the Phonenumber
	 */
	public String getPhonenumber() {
	    return this.phonenumber;
	}
	
	/**
	 *@param sex the sex to set
	 */
	public void setSex(String sex) {
		this.sex=sex;
	}
		
	/**
	 *@return the Sex
	 */
	public String getSex() {
	    return this.sex;
	}
	
	/**
	 *@param avatar the avatar to set
	 */
	public void setAvatar(String avatar) {
		this.avatar=avatar;
	}
		
	/**
	 *@return the Avatar
	 */
	public String getAvatar() {
	    return this.avatar;
	}
	
	/**
	 *@param password the password to set
	 */
	public void setPassword(String password) {
		this.password=password;
	}
		
	/**
	 *@return the Password
	 */
	public String getPassword() {
	    return this.password;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param delFlag the delFlag to set
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag=delFlag;
	}
		
	/**
	 *@return the DelFlag
	 */
	public String getDelFlag() {
	    return this.delFlag;
	}
	
	/**
	 *@param loginIp the loginIp to set
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp=loginIp;
	}
		
	/**
	 *@return the LoginIp
	 */
	public String getLoginIp() {
	    return this.loginIp;
	}
	
	/**
	 *@param loginDate the loginDate to set
	 */
	public void setLoginDate(LocalDateTime loginDate) {
		this.loginDate=loginDate;
	}
		
	/**
	 *@return the LoginDate
	 */
	public LocalDateTime getLoginDate() {
	    return this.loginDate;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark=remark;
	}
		
	/**
	 *@return the Remark
	 */
	public String getRemark() {
	    return this.remark;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(String id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 *@param revision the revision to set
	 */
	public void setRevision(Integer revision) {
		this.revision=revision;
	}
		
	/**
	 *@return the Revision
	 */
	public Integer getRevision() {
	    return this.revision;
	}
	
	/**
	 *@param createBy the createBy to set
	 */
	public void setCreateBy(String createBy) {
		this.createBy=createBy;
	}
		
	/**
	 *@return the CreateBy
	 */
	public String getCreateBy() {
	    return this.createBy;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(LocalDateTime createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public LocalDateTime getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public LocalDateTime getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param deleteStatus the deleteStatus to set
	 */
	public void setDeleteStatus(String deleteStatus) {
		this.deleteStatus=deleteStatus;
	}
		
	/**
	 *@return the DeleteStatus
	 */
	public String getDeleteStatus() {
	    return this.deleteStatus;
	}
	
	/**
	 *@param username the username to set
	 */
	public void setUsername(String username) {
		this.username=username;
	}
		
	/**
	 *@return the Username
	 */
	public String getUsername() {
	    return this.username;
	}
	
	/**
	 *@param nickname the nickname to set
	 */
	public void setNickname(String nickname) {
		this.nickname=nickname;
	}
		
	/**
	 *@return the Nickname
	 */
	public String getNickname() {
	    return this.nickname;
	}
	
	/**
	 *@param password the password to set
	 */
	public void setPassword(String password) {
		this.password=password;
	}
		
	/**
	 *@return the Password
	 */
	public String getPassword() {
	    return this.password;
	}
	
	/**
	 *@param sex the sex to set
	 */
	public void setSex(String sex) {
		this.sex=sex;
	}
		
	/**
	 *@return the Sex
	 */
	public String getSex() {
	    return this.sex;
	}
	
	/**
	 *@param email the email to set
	 */
	public void setEmail(String email) {
		this.email=email;
	}
		
	/**
	 *@return the Email
	 */
	public String getEmail() {
	    return this.email;
	}
	
	/**
	 *@param mobilephone the mobilephone to set
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone=mobilephone;
	}
		
	/**
	 *@return the Mobilephone
	 */
	public String getMobilephone() {
	    return this.mobilephone;
	}
	
	/**
	 *@param departmentId the departmentId to set
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId=departmentId;
	}
		
	/**
	 *@return the DepartmentId
	 */
	public String getDepartmentId() {
	    return this.departmentId;
	}
	
	/**
	 *@param accountStatus the accountStatus to set
	 */
	public void setAccountStatus(String accountStatus) {
		this.accountStatus=accountStatus;
	}
		
	/**
	 *@return the AccountStatus
	 */
	public String getAccountStatus() {
	    return this.accountStatus;
	}
	
	/**
	 *@param avatar the avatar to set
	 */
	public void setAvatar(String avatar) {
		this.avatar=avatar;
	}
		
	/**
	 *@return the Avatar
	 */
	public String getAvatar() {
	    return this.avatar;
	}
	
	/**
	 *@param lastLoginIp the lastLoginIp to set
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp=lastLoginIp;
	}
		
	/**
	 *@return the LastLoginIp
	 */
	public String getLastLoginIp() {
	    return this.lastLoginIp;
	}
	
	/**
	 *@param lastLoginTime the lastLoginTime to set
	 */
	public void setLastLoginTime(LocalDateTime lastLoginTime) {
		this.lastLoginTime=lastLoginTime;
	}
		
	/**
	 *@return the LastLoginTime
	 */
	public LocalDateTime getLastLoginTime() {
	    return this.lastLoginTime;
	}
/*---end-auto-generate-don't-update-this-area--*/	
}
