DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role(
    ID VARCHAR(32) NOT NULL   COMMENT '主键id' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATE_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_STATUS CHAR(1) NOT NULL   COMMENT '删除状态;0删除 1未删除' ,
    ROLE_NAME VARCHAR(30) NOT NULL   COMMENT '角色名称' ,
    ROLE_KEY VARCHAR(255) NOT NULL   COMMENT '角色标识' ,
    SORT INT NOT NULL   COMMENT '显示排序' ,
    REMARK VARCHAR(255)    COMMENT '备注' ,
    PRIMARY KEY (ID)
)  COMMENT = '系统角色表';

DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user(
    ID VARCHAR(32) NOT NULL   COMMENT '主键id' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATE_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_STATUS CHAR(1) NOT NULL   COMMENT '删除状态;0删除 1未删除' ,
    USERNAME VARCHAR(30) NOT NULL   COMMENT '用户账号' ,
    NICKNAME VARCHAR(30) NOT NULL   COMMENT '用户昵称' ,
    PASSWORD VARCHAR(32) NOT NULL   COMMENT '密码' ,
    SEX CHAR(1) NOT NULL   COMMENT '用户性别;0未知 1男 2女' ,
    EMAIL VARCHAR(64)    COMMENT '用户邮箱' ,
    MOBILEPHONE VARCHAR(11)    COMMENT '手机号' ,
    DEPARTMENT_ID VARCHAR(32)    COMMENT '部门id' ,
    ACCOUNT_STATUS CHAR(1) NOT NULL   COMMENT '账号状态;0停用 1正常 2冻结 3封禁' ,
    AVATAR VARCHAR(255)    COMMENT '头像地址' ,
    LAST_LOGIN_IP VARCHAR(64)    COMMENT '最后登录IP' ,
    LAST_LOGIN_TIME DATETIME    COMMENT '最后登录时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '系统用户表';

DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu(
    ID VARCHAR(32) NOT NULL   COMMENT '主键id' ,
    REVISION INT    COMMENT '乐观锁' ,
    CREATE_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_STATUS VARCHAR(255)    COMMENT '删除状态;0删除 1未删除' ,
    MENU_NAME VARCHAR(30) NOT NULL   COMMENT '菜单名称' ,
    PERMISSION_CODE VARCHAR(64) NOT NULL   COMMENT '权限编号' ,
    ROUTER_PATH VARCHAR(255) NOT NULL   COMMENT '路由地址' ,
    PARENT_ID VARCHAR(32)    COMMENT '父主键ID' ,
    MENU_TYPE CHAR(1) NOT NULL   COMMENT '按钮类型;0目录 1菜单 2按钮' ,
    IS_MENU CHAR(1) NOT NULL   COMMENT '是否菜单' ,
    SORT INT NOT NULL   COMMENT '显示顺序' ,
    COMPONENT_PATH VARCHAR(64)    COMMENT '组件路径' ,
    IS_EXTERNAL_LINK CHAR(1) NOT NULL   COMMENT '是否外链;0是 1否' ,
    ICON_PATH VARCHAR(255)    COMMENT '菜单图标' ,
    PRIMARY KEY (ID)
)  COMMENT = '系统菜单表';

DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role(
    USER_ID VARCHAR(32) NOT NULL   COMMENT '用户主键ID' ,
    ROLE_ID VARCHAR(32) NOT NULL   COMMENT '角色主键ID' 
)  COMMENT = '用户角色关联表';

DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu(
    ROLE_ID VARCHAR(32) NOT NULL   COMMENT '角色主键ID' ,
    MENU_ID VARCHAR(32) NOT NULL   COMMENT '菜单主键ID' 
)  COMMENT = '角色菜单关联表';

