name: Generate Changelog

on:
  push:
    branches:
      - dev
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' 

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git checkout 'origin/main'
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add CHANGELOG.md

          # 如果没有更改，跳过提交
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "docs: update CHANGELOG.md"
          git push origin main  # 推送到 main 分支
          # git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git 'main'
